(cl:in-package hrs_project-srv)
(cl:export '(JOINT_NAME-VAL
          JOINT_NAME
          END_EFFECTOR-VAL
          END_EFFECTOR
          GOAL_6DPOSITION_MARKER-VAL
          GOAL_6DPOSITION_MARKER
          GOAL_6DPOSITION_CLOTH-VAL
          GOAL_6DPOSITION_CLOTH
          GOAL_6DPOSITION-VAL
          GOAL_6DPOSITION
          SPEEDORTIME-VAL
          SPEEDORTIME
          AXISMASK-VAL
          AXISMASK
          CONTROL_MOD-VAL
          CONTROL_MOD
          GETMARKER-VAL
          GETMARKER
          GETMARKER_GROUND-VAL
          GETMARKER_GROUND
          CLOTH_COLOR-VAL
          CLOTH_COLOR
          NUM-VAL
          NUM
          ROSEPICK_READY-VAL
          ROSEPICK_READY
          BMARKERARRIVED-VAL
          BMARKERARRIVED
          SPEECHCOMMAND-VAL
          SPEECHCOMMAND
))