// Generated by gencpp from file hrs_project/BlinkResult.msg
// DO NOT EDIT!


#ifndef HRS_PROJECT_MESSAGE_BLINKRESULT_H
#define HRS_PROJECT_MESSAGE_BLINKRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hrs_project
{
template <class ContainerAllocator>
struct BlinkResult_
{
  typedef BlinkResult_<ContainerAllocator> Type;

  BlinkResult_()
    : still_blinking(false)  {
    }
  BlinkResult_(const ContainerAllocator& _alloc)
    : still_blinking(false)  {
  (void)_alloc;
    }



   typedef uint8_t _still_blinking_type;
  _still_blinking_type still_blinking;





  typedef boost::shared_ptr< ::hrs_project::BlinkResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hrs_project::BlinkResult_<ContainerAllocator> const> ConstPtr;

}; // struct BlinkResult_

typedef ::hrs_project::BlinkResult_<std::allocator<void> > BlinkResult;

typedef boost::shared_ptr< ::hrs_project::BlinkResult > BlinkResultPtr;
typedef boost::shared_ptr< ::hrs_project::BlinkResult const> BlinkResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hrs_project::BlinkResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hrs_project::BlinkResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hrs_project

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'hrs_project': ['/home/nao_a/ros/hrs_project/devel/.private/hrs_project/share/hrs_project/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hrs_project::BlinkResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hrs_project::BlinkResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hrs_project::BlinkResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hrs_project::BlinkResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hrs_project::BlinkResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hrs_project::BlinkResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hrs_project::BlinkResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "53e041b81450f9247036f13b3c0bf822";
  }

  static const char* value(const ::hrs_project::BlinkResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x53e041b81450f924ULL;
  static const uint64_t static_value2 = 0x7036f13b3c0bf822ULL;
};

template<class ContainerAllocator>
struct DataType< ::hrs_project::BlinkResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hrs_project/BlinkResult";
  }

  static const char* value(const ::hrs_project::BlinkResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hrs_project::BlinkResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
bool still_blinking\n\
";
  }

  static const char* value(const ::hrs_project::BlinkResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hrs_project::BlinkResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.still_blinking);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BlinkResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hrs_project::BlinkResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hrs_project::BlinkResult_<ContainerAllocator>& v)
  {
    s << indent << "still_blinking: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.still_blinking);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HRS_PROJECT_MESSAGE_BLINKRESULT_H
