// Generated by gencpp from file hrs_project/MoveJoints.msg
// DO NOT EDIT!


#ifndef HRS_PROJECT_MESSAGE_MOVEJOINTS_H
#define HRS_PROJECT_MESSAGE_MOVEJOINTS_H

#include <ros/service_traits.h>


#include <hrs_project/MoveJointsRequest.h>
#include <hrs_project/MoveJointsResponse.h>


namespace hrs_project
{

struct MoveJoints
{

typedef MoveJointsRequest Request;
typedef MoveJointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveJoints
} // namespace hrs_project


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hrs_project::MoveJoints > {
  static const char* value()
  {
    return "904bb3e81ce1f0698f6188c53777d573";
  }

  static const char* value(const ::hrs_project::MoveJoints&) { return value(); }
};

template<>
struct DataType< ::hrs_project::MoveJoints > {
  static const char* value()
  {
    return "hrs_project/MoveJoints";
  }

  static const char* value(const ::hrs_project::MoveJoints&) { return value(); }
};


// service_traits::MD5Sum< ::hrs_project::MoveJointsRequest> should match 
// service_traits::MD5Sum< ::hrs_project::MoveJoints > 
template<>
struct MD5Sum< ::hrs_project::MoveJointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hrs_project::MoveJoints >::value();
  }
  static const char* value(const ::hrs_project::MoveJointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hrs_project::MoveJointsRequest> should match 
// service_traits::DataType< ::hrs_project::MoveJoints > 
template<>
struct DataType< ::hrs_project::MoveJointsRequest>
{
  static const char* value()
  {
    return DataType< ::hrs_project::MoveJoints >::value();
  }
  static const char* value(const ::hrs_project::MoveJointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hrs_project::MoveJointsResponse> should match 
// service_traits::MD5Sum< ::hrs_project::MoveJoints > 
template<>
struct MD5Sum< ::hrs_project::MoveJointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hrs_project::MoveJoints >::value();
  }
  static const char* value(const ::hrs_project::MoveJointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hrs_project::MoveJointsResponse> should match 
// service_traits::DataType< ::hrs_project::MoveJoints > 
template<>
struct DataType< ::hrs_project::MoveJointsResponse>
{
  static const char* value()
  {
    return DataType< ::hrs_project::MoveJoints >::value();
  }
  static const char* value(const ::hrs_project::MoveJointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HRS_PROJECT_MESSAGE_MOVEJOINTS_H
